name: Android Artifact Build

on:
  push:
    paths:
      - '/android/**' # Triggers the workflow on changes to any file in the repository

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants permission to push code and manage releases
      pull-requests: write  # Grants permission to write pull requests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check for Repo changes
        run: |
          if git diff --quiet HEAD^ HEAD -- 'path/android/**'; then
          echo "No changes in directory"
          exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
            node-version: '16'

      - name: Install npm dependencies
        run: |
            npm install -g yarn # Install yarn globally if you're using yarn
            yarn install # or `npm install` if using npm

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build Artifact
        run: |
            cd android
            chmod +x ./gradlew
            ./gradlew assembleDebug

      - name: Replace Existing Artifact
        run: |
          ls -la ./android/build/outputs/aar/
          mkdir -p ./artefacts/tuvali-android-artefact/
          cp ./android/build/outputs/aar/*.aar ./artefacts/tuvali-android-artefact/

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit Artifacts
        run: |
          git add .
          git commit --allow-empty -m "chore(#890): changes in script"

      - name: Push Changes to Specific Branch
        run: |
              git pull --rebase
              git push origin inji-Kotlin-ios-artefact
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

